version: '3'
services:
  postgresql:
    image: postgres:15.1
    container_name: postgresql
    networks:
      - localstack-net
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ruah
      - POSTGRES_USER=ruah
      - POSTGRES_PASSWORD=ruah

networks:
  localstack-net:
    driver: bridge  